services:
  app:
    image: auth_api_php83:latest
    container_name: auth_api_app
    pull_policy: never
    build:
      context: ./docker/php83
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"  # Порт FPM

  postgres:
    image: auth_api-postgres:latest
    container_name: auth_api_postgres
    pull_policy: never
    build:
      context: ./docker/postgres
      args:  # Явно передаём переменные как build-args
        DB_DATABASE: ${DB_DATABASE:-auth_api}
        DB_USERNAME: ${DB_USERNAME:-auth_api_user}
        DB_PASSWORD: ${DB_PASSWORD:-auth_api_password}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-auth_api_password}  # Пароль суперпользователя
      DB_DATABASE: ${DB_DATABASE:-auth_api}
      DB_USERNAME: ${DB_USERNAME:-auth_api_user}
      DB_PASSWORD: ${DB_PASSWORD:-auth_api_password}
      DB_PORT: ${DB_PORT:-5432}
    ports:
      - "${HOST_DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  caddy:
    image: auth_api-caddy:latest
    container_name: auth_api_caddy
    pull_policy: never
    build:
      context: ./docker/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ./:/var/www
    depends_on:
      - app

  mailpit:
    image: auth_api-mailpit:latest
    container_name: auth_api_mailpit
    pull_policy: never
    build:
      context: ./docker/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data

volumes:
  pg_data:
    name: auth_api_pg_data
  caddy_data:
    name: auth_api_caddy_data
  mailpit_data:
    name: auth_api_mailpit_data
